// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class MyCourseView
{
    public int CourseId { get; set; }

    public string Title { get; set; }

    public string DepartmentName { get; set; }
}